### ISSUE TITLE
Custom SVG shapes in UML profile

### ISSUE THREAD

**Issue by gerasimou** [epsilonlabs/SACM-UML-Profile#14]
Custom SVG shapes do not appear in new UML models that conform to a UML profile.

Papyrus throws an "Uncaught exception in transaction pre-commit task" in org.eclipse.papyrus.infra.core plugin. Asked in Papyrus forum for help (post hasn't appeared on the forum yet)

**Comment by zolotas4** [comment]
I asked a relative question on how to attach css stylesheets to the profile plugin project so they are loaded automatically with the registered profile [here](https://www.eclipse.org/forums/index.php/m/1755524/#msg_1755524).

**Comment by zolotas4** [comment]
Commit 4582bd432cde0bd2de4cf15aaa871da1ed6a31c4 adds the automatic generation of 1) the Image element in the profile that is annotated with shape details, 2) the path of the shape image. The only problem is that in order to have the shape shown, we need to apply the style.css added in this commit to the diagram we create using the automatically generated profile. Asked the forum for an automatic solution.

**Comment by zolotas4** [comment]
The source code of Archimate for Papyrus is available here: https://t.co/kdzkn8kW6M

They use a different way to implement the palette and the shapes. *Might* be an overkill for our approach but we should investigate.

**Comment by zolotas4** [comment]
The creation of the palette.xml file for custom palettes and diagrams is not suggested. Instead [Viewpoints](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.papyrus.infra.viewpoints.doc%2Ftarget%2Fgenerated-eclipse-help%2Fviewpoints.html) should be used. I still have problem creating the shapes similar to the one asked [here](https://www.eclipse.org/forums/index.php/t/1082514/).

**Comment by zolotas4** [comment]
Some shapes now appear on the diagram after commit de741a7a76cf7880458c9823dd564912efa8cd18
Need to think what happens with types that have no shape assigned (probably a default shape should be used). In addition, I absolutely ignored associations in my generation scripts in these minimal examples. I need to include these as well and check how they perform.

**Comment by zolotas4** [comment]
I tested the implementation using SVG shapes from the Archimate for Papyrus tool. The exception is never thrown. I believe that the problem is with some SVG shapes (the way they are constructed). Asked the forum if anyone has information on what are the properties of the "bad" SVG files to avoid using them until this problem/bug is fixed.

**Comment by zolotas4** [comment]
This is now solved. Papyrus needs to have the width/height of the shape stored in pixels in the SVG file. In the shapes we were using this was set to another unit (e.g., mm, pt, ...) or not set at all. See my detailed explanation [here](https://www.eclipse.org/forums/index.php?t=msg&th=1084780&goto=1756164&#msg_1756164).
